-- ============================================================================
-- New Tenant Provisioning Script
-- ============================================================================
-- Creates a fully-provisioned tenant where:
--   • tenant.id   = uuidv7()    (generated by DB)
--   • tenant.slug = tenant.id   (UUID string, guaranteed unique)
--   • tenant.name = tenant.id   (same UUID, used as display name)
--
-- No collision checks needed — UUIDs are globally unique by definition.
--
-- Seeds:
--   • widget_configuration      (via bootstrap_tenant_defaults trigger)
--   • persona_configurations    (cloned from bootstrap tenant)
--   • security_settings         (cloned from bootstrap tenant)
--   • llm_providers             (cloned from bootstrap tenant)
--   • user row in public.users  (created if email does not exist yet)
--   • admin role mapping        (M2M — user can be admin on many tenants)
--   • notification_settings for the admin
--
-- USAGE:
--   Edit v_admin_email below, then run:
--       psql "$DATABASE_URL" -f sql/scripts/provision_new_tenant.sql
-- ============================================================================

DO $$
DECLARE
    -- ----------------------------------------------------------------
    -- ✏️  ONLY THIS ONE VALUE NEEDS TO BE SET
    -- ----------------------------------------------------------------
    v_admin_email   TEXT := 'admin@example.com';   -- ← admin's email
    -- ----------------------------------------------------------------

    v_tenant_id     UUID;
    v_tenant_ref    TEXT;   -- text form of the UUID, used for slug + name
    v_user_id       UUID;
    v_admin_role_id UUID;
    v_user_role_id  UUID;
BEGIN
    -- ----------------------------------------------------------------
    -- 0. M2M notice: same admin can belong to multiple tenants
    -- ----------------------------------------------------------------
    IF EXISTS (
        SELECT 1
        FROM public.user_role_mapping urm
        JOIN public.users u ON u.id = urm.user_id
        JOIN public.roles r ON r.id = urm.role_id
        WHERE u.email = v_admin_email AND r.role_name = 'admin'
        LIMIT 1
    ) THEN
        RAISE NOTICE 'ℹ️  "%" is already admin on other tenant(s) — M2M is supported, adding them here too.', v_admin_email;
    END IF;

    -- Generate the UUID ourselves so we can use it as slug + name
    -- in the same INSERT statement (trigger fires with correct values).
    v_tenant_id  := uuidv7();           -- or gen_random_uuid() if uuidv7 unavailable
    v_tenant_ref := v_tenant_id::text;

    INSERT INTO public.tenants (id, slug, name, description, is_active, metadata)
    VALUES (
        v_tenant_id,
        v_tenant_ref,   -- slug  = UUID string
        v_tenant_ref,   -- name  = UUID string
        'Provisioned via provision_new_tenant.sql',
        true,
        jsonb_build_object(
            'seeded_by',   'provision_new_tenant.sql',
            'admin_email', v_admin_email,
            'created_at',  CURRENT_TIMESTAMP
        )
    );

    RAISE NOTICE '✅ Tenant created (id = slug = name = %)', v_tenant_ref;


    -- ----------------------------------------------------------------
    -- 2. Upsert the user (create if they don't exist yet)
    -- ----------------------------------------------------------------
    INSERT INTO public.users (email, is_active, created_at, updated_at)
    VALUES (v_admin_email, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    ON CONFLICT (email)
        DO UPDATE SET is_active = true, updated_at = CURRENT_TIMESTAMP
    RETURNING id INTO v_user_id;

    RAISE NOTICE '✅ User upserted: % (id=%)', v_admin_email, v_user_id;

    -- ----------------------------------------------------------------
    -- 3. Resolve 'admin' role id
    -- ----------------------------------------------------------------
    SELECT id INTO v_admin_role_id
    FROM public.roles
    WHERE role_name = 'admin'
    LIMIT 1;

    IF v_admin_role_id IS NULL THEN
        RAISE EXCEPTION 'No role named "admin" found in public.roles. Check your roles table.';
    END IF;

    -- ----------------------------------------------------------------
    -- 4. Create the admin role mapping (M2M — one user, many tenants)
    --    ON CONFLICT uses column list because the unique key is an INDEX,
    --    not a named CONSTRAINT.
    -- ----------------------------------------------------------------
    INSERT INTO public.user_role_mapping (
        user_id, role_id, tenant_id, is_active, created_at, updated_at
    )
    VALUES (
        v_user_id, v_admin_role_id, v_tenant_id,
        true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    )
    ON CONFLICT (user_id, role_id, tenant_id)
        DO UPDATE SET is_active = true, updated_at = CURRENT_TIMESTAMP
    RETURNING user_role_id INTO v_user_role_id;

    RAISE NOTICE '✅ Admin role mapping created (user_role_id=%)', v_user_role_id;

    -- ----------------------------------------------------------------
    -- 5. Seed notification_settings for the admin
    -- ----------------------------------------------------------------
    INSERT INTO public.notification_settings (
        tenant_id, user_email,
        notify_new_chat, notify_human_request, notify_feedback,
        created_at, updated_at
    )
    VALUES (
        v_tenant_id, v_admin_email,
        true, true, true,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    )
    ON CONFLICT DO NOTHING;

    RAISE NOTICE '✅ Notification settings seeded for %', v_admin_email;

    -- ----------------------------------------------------------------
    -- 6. Summary
    -- ----------------------------------------------------------------
    RAISE NOTICE '';
    RAISE NOTICE '============================================================';
    RAISE NOTICE '  NEW TENANT PROVISIONED SUCCESSFULLY';
    RAISE NOTICE '============================================================';
    RAISE NOTICE '  Tenant ID    : %', v_tenant_ref;
    RAISE NOTICE '  Tenant Slug  : %', v_tenant_ref;
    RAISE NOTICE '  Tenant Name  : %', v_tenant_ref;
    RAISE NOTICE '  Admin Email  : %', v_admin_email;
    RAISE NOTICE '  Admin User ID: %', v_user_id;
    RAISE NOTICE '============================================================';
    RAISE NOTICE '';
    RAISE NOTICE 'Next steps:';
    RAISE NOTICE '  • Send the admin a sign-in link / password reset.';
    RAISE NOTICE '  • Pass X-Tenant-ID: % in API calls for this tenant.', v_tenant_ref;

END $$;
