"""
Consolidated Chatbot Orchestration Router
All chatbot orchestration endpoints in one file for easier debugging
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from typing import Dict, List, Any, Optional
import logging
import time

from ..service.chat_service import ChatService
from ..service.agent_service import PydanticAIGatewayService
from ..schemas.models import ChatRequest
from ..dao.session_persistence_dao import SessionPersistenceDAO

logger = logging.getLogger(__name__)
from ..core.utils import log_endpoint_request

router = APIRouter()

# Initialize services
chat_service = ChatService()
agent_service = PydanticAIGatewayService()

# =================================
# CHAT ENDPOINTS (STREAMING ONLY)
# =================================

@router.post("/chat/stream")
async def chat_with_agent_stream(request: Request):
    """Chat with AI agent with streaming response using Pydantic AI"""
    try:
        body = await request.json()

        message = body.get("message")
        session_id = body.get("session_id")

        if not message:
            raise HTTPException(status_code=400, detail="Message is required")

        # Create session if not provided
        if not session_id:
            session_id = f"session_{int(time.time())}"

        # Stream response (tools are configured internally in agent_manager)
        async def generate_response():
            async for chunk in agent_service.stream_agent_response(message, session_id):
                yield chunk

        return StreamingResponse(
            generate_response(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "X-Accel-Buffering": "no"
            }
        )
    except Exception as e:
        logger.error(f"Error in chat stream: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/chat/history/{session_id}")
async def get_chat_history(session_id: str):
    """Get chat history for a session"""
    try:
        history = await chat_service.get_chat_history(session_id)
        
        return {
            "success": True,
            "history": history,
            "session_id": session_id
        }
    except Exception as e:
        logger.error(f"Error getting chat history: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.delete("/chat/session/{session_id}")
async def delete_chat_session(session_id: str):
    """Delete a chat session"""
    try:
        result = await chat_service.delete_session(session_id)
        
        return {
            "success": True,
            "message": "Session deleted successfully"
        }
    except Exception as e:
        logger.error(f"Error deleting session: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/chat/session")
async def create_chat_session(request: Request):
    """Create a new chat session"""
    try:
        body = await request.json()
        
        agent_id = body.get("agent_id", "default")
        
        session_id = f"session_{int(time.time())}"
        
        return {
            "success": True,
            "session_id": session_id,
            "agent_id": agent_id
        }
    except Exception as e:
        logger.error(f"Error creating session: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/chat/sessions")
async def get_user_sessions():
    """Get all chat sessions"""
    try:
        sessions = await chat_service.get_all_sessions()

        return {
            "success": True,
            "sessions": sessions
        }
    except Exception as e:
        logger.error(f"Error getting sessions: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/sessions/numeric-id/{uuid_session_id}")
async def get_or_create_session_numeric_id(uuid_session_id: str):
    """
    Register a session with its UUID and get back the numeric database ID.
    Frontend calls this when creating a new session to get the numeric ID for session-level operations.

    Args:
        uuid_session_id: UUID-style session ID generated by frontend (e.g., session_1772521413864_5o610dbd1)

    Returns:
        {"success": True, "data": {"id": <numeric_id>, "session_id": "<uuid>"}}
    """
    try:
        if not uuid_session_id or not uuid_session_id.strip():
            raise HTTPException(status_code=400, detail="uuid_session_id is required")

        # Use SessionPersistenceDAO to get or create the session
        session_dao = SessionPersistenceDAO()
        numeric_id = await session_dao.get_or_create_session(uuid_session_id)

        logger.info(f"✅ Got numeric ID {numeric_id} for session {uuid_session_id}")

        return {
            "success": True,
            "data": {
                "id": numeric_id,
                "session_id": uuid_session_id
            }
        }
    except Exception as e:
        logger.error(f"Error getting/creating session numeric ID: {e}")
        raise HTTPException(status_code=500, detail=str(e))

# =================================
# HEALTH ENDPOINTS
# =================================

@router.get("/health")
async def health_check():
    """Health check endpoint"""
    try:
        health_status = {
            "status": "healthy",
            "service": "chatbot_orchestration",
            "timestamp": "2024-01-01T00:00:00Z",
            "components": {
                "chat_service": "healthy",
                "agent_service": "healthy",
                "database": "connected"
            }
        }
        return health_status
    except Exception as e:
        logger.error(f"Health check failed: {e}")
        raise HTTPException(status_code=500, detail=f"Health check failed: {str(e)}")
